//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetrisReturn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TetrisReturn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Amazing {
            get {
                return ResourceManager.GetStream("Amazing", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Brilliant {
            get {
                return ResourceManager.GetStream("Brilliant", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Clear {
            get {
                return ResourceManager.GetStream("Clear", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Click {
            get {
                return ResourceManager.GetStream("Click", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Dis_appear {
            get {
                return ResourceManager.GetStream("Dis_appear", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Excellent {
            get {
                return ResourceManager.GetStream("Excellent", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Fall {
            get {
                return ResourceManager.GetStream("Fall", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream GameOver {
            get {
                return ResourceManager.GetStream("GameOver", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream GameWin {
            get {
                return ResourceManager.GetStream("GameWin", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Hover {
            get {
                return ResourceManager.GetStream("Hover", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream LeftRightFail {
            get {
                return ResourceManager.GetStream("LeftRightFail", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream LevelUp {
            get {
                return ResourceManager.GetStream("LevelUp", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Lock {
            get {
                return ResourceManager.GetStream("Lock", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream MoveLeftRight {
            get {
                return ResourceManager.GetStream("MoveLeftRight", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Rotate {
            get {
                return ResourceManager.GetStream("Rotate", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream RotateFail {
            get {
                return ResourceManager.GetStream("RotateFail", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Theme {
            get {
                return ResourceManager.GetStream("Theme", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream VeryGood {
            get {
                return ResourceManager.GetStream("VeryGood", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Wonderful {
            get {
                return ResourceManager.GetStream("Wonderful", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Wow {
            get {
                return ResourceManager.GetStream("Wow", resourceCulture);
            }
        }
    }
}
